logging:
  file: /opt/apps/moneytap/logs/first-practice/rest.log

jwt:
  issuer: moneytap-idm
  certificates:
    - keyId: RSA20200618_01
      keyType: RSA
      algorithm: RS256
      publicKey: MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA19diNlYinurEnZKLKmNb+3aYi+qgEnlDqE8sSjRRYL+xglnclOeD2Vs2odmNMjDFw/odac6WYyQacxuazWKxGYvC0HZKCMFKYc4Y0vpxLaiACY7c9yQ5JRzRZw61qrdpfGXrmqFpRxuab6gJhLdXFDlz/FOCwEEBrI2QnWQssi3IWccwY8fg7HDyPbkjzIRcSHmRlBXBA5gorHmGL8Ur34a1fGGLyBW9PKbSVo0EY9Lhw6xU3ZtCxfb9jcZ0uDmdisocrrWKZTkJPnman53DSeb1RsvH3LVqS9wMdvI0zEtOzXZve0ItENvw8LgzzF/1SPJnhlVQ/+aliyLXm2AY9QijyRc6O0pCvecYhMgzPhXT3MZ84NoGF2Q3hc57URRU3mo+VMvDFgfeqZ/RT/uf83DmVO7JEMtQBQoPAZmrcrwYJ9OQOErrkg6AsG3+e6LqoRJTUHa3wEk/iLsApe5dhNDn1ontDBd2Q8RuavOHAanXMAKoWcAt84Gwq9kvT7jt27BLax2hXvJjPtTEUmwvYGgBlz5xj9bCGEMYZqXrTCSJ3D4/U9TyfNy8xuIt9GylE6lqRglZSFcJt39XWRmGci6Slmb4Xh/cvAABLCS6AmYbq3tyu7FMIwmXw0lQyHmXZ9r4/9j7pwFGPybq/INKSN632coJkzE6pMklQ7g5jQ0CAwEAAQ==
      privateKey: MIIJQwIBADANBgkqhkiG9w0BAQEFAASCCS0wggkpAgEAAoICAQDX12I2ViKe6sSdkosqY1v7dpiL6qASeUOoTyxKNFFgv7GCWdyU54PZWzah2Y0yMMXD+h1pzpZjJBpzG5rNYrEZi8LQdkoIwUphzhjS+nEtqIAJjtz3JDklHNFnDrWqt2l8ZeuaoWlHG5pvqAmEt1cUOXP8U4LAQQGsjZCdZCyyLchZxzBjx+DscPI9uSPMhFxIeZGUFcEDmCiseYYvxSvfhrV8YYvIFb08ptJWjQRj0uHDrFTdm0LF9v2NxnS4OZ2KyhyutYplOQk+eZqfncNJ5vVGy8fctWpL3Ax28jTMS07Ndm97Qi0Q2/DwuDPMX/VI8meGVVD/5qWLItebYBj1CKPJFzo7SkK95xiEyDM+FdPcxnzg2gYXZDeFzntRFFTeaj5Uy8MWB96pn9FP+5/zcOZU7skQy1AFCg8BmatyvBgn05A4SuuSDoCwbf57ouqhElNQdrfAST+IuwCl7l2E0OfWie0MF3ZDxG5q84cBqdcwAqhZwC3zgbCr2S9PuO3bsEtrHaFe8mM+1MRSbC9gaAGXPnGP1sIYQxhmpetMJIncPj9T1PJ83LzG4i30bKUTqWpGCVlIVwm3f1dZGYZyLpKWZvheH9y8AAEsJLoCZhure3K7sUwjCZfDSVDIeZdn2vj/2PunAUY/Jur8g0pI3rfZygmTMTqkySVDuDmNDQIDAQABAoICAQCrOawp2s8ALtHnBtfruoK/y+dcJ7bwsM5heN1zyGk+TRPuiocYgUjxZxDB+KmwRUy+GW63/zECWSO6aQ23HTHNSDg104ELzPrK+AptZEvgoqlf67uTO2Mx89iS3vJzCalfDCOJub6gsF8lcLKMXD1yR9mhNEanaWqAjpVIpq1mdDdaMVBL98aRC1DAclzZ466pt/cq+M7zoQOzP3yZ7NrPKjhTAbc39Tb4JIb8LkZrQmHjLpTscDzaewPOMr9pXhuCfK+gUVgG0OZqb2GgejDwMY4mqYZVqn02zMv+mEoWPy+2gtwRdf/2PeS3sgk1enJFejdyM8BcIYb2B5/vHJ7uXhvDVT7TKoXeuDRQgwfiLKADVCWNxcPbBNUmoiZxFmDi2KbAuk4ag4w0AaEUiuG1/XYFYUjznHwzRplo1jCmGC8TMhvuGBHdCDCQvkyleYUgbJZesctpWzVnqiusUbTOlBZV1p8XAjilrf53c8bJg+E23Qojvr4WDxxgP31m5WaRqt0mF1fpd1mGAIV7JM6++SZeEeJ+cRfIXpO1EJmjNIZFYDBPiGYNB+yiUBWf+hXyU0HrzRwM695YkMbVbHZCs0bV6fg0S6oiFAE11vJeVUsTEqKLURPSxElV37XiAndy8vZGkhIlAiuwWfZPYmB/t8HqZNRS37jFV2KC16zVwQKCAQEA/Bo1EgczSd0k5jbUEwciOliE1oWyyOrwf27pDPLyfKhUt12/d27tSRdHPNW8CpnHHFgceoh+3//NwkUr5BtiZwxevQnbIofRmW6Rpdydx4a0BJgKUiQrAGCqQzCQZiONQEAXKeQPXNs7r9NjjUcRq7rpO/FYQP8k6S3J/mFKq8z+6gveocmeS7IbTFpFSkH2SfVoTNd/I44D98mWSESThWrvGVmbRvjSovSXRGSyghIbjC/7PMT3cTAQARQECdkVnPrK81p/y5cVNcKLlNIpVqSfHGYHGk6Z4WQ2Q+eOGp8FpiPPvODqNltttcMaQNYI9eM085lB1QwQGaDPD6JYxQKCAQEA2y2oxmhMHSXne296mxKx5lLWteMjus84OQ1z62lA4HsQqyOA/OxYy6qZxdyTTTNaCgaFJ3SczdbM7/DBzuyLoCvI7LHVCb4kP0/xEp23f37IKgz1DaFJNJb20IHygXSNOzWHv6ezPwYtxpGlfSo8YXGx3NanUuCXAemrYsTFQG3ymbigNPxuupcI6dLntWH8qCZnGJjpUdgzG2CFwWiUuYGdNxGLzTOnLssPeofMFfmN5aTkX9aDscmFYkcfbqdABYG6r7BuRNaMD84OD9In+/0PCqJRNIYjiNR1E0xJNdPoyauNfL1kcbrbBqBPGMmfNTG3kKHa3j8y9nGa/HpXqQKCAQBX/WWshyrViwQH/fcDNSgzKRYkMcH28llCgRmCVYFhFPeMkIH1U5gqPJ+2kfrx0D54nCBEfEOcNxI/zhjFovEzelPOsxPy92imnrrjIx9GtrM6Lz7a8Ji5pwOGM/sSSzJPzI7JJjpedH5ene9PLhDy2WfybggZl3PwlvS7foWrdP87/SyVV2OSk/WHLrKkemVV5vuiZkyPwk+MOqXjT1wV4v7U4DucB9is26W4T1UmpN9MjKqpyS18KgRL/Ap0zXoHslkHmvyjuHXEr8Q8CyY2gXqvVMUB35FB49I03SryC7LTDAjDqdTVaA/gstoE6y9xcv3WUBV0IKO17jSXBljpAoIBAQC4Mk4luB9HW8SHWu+6BWMWwsWJBIPRijag0+p4i/Mm9KXUfbj4VhRlzVEAFNiCR8bCqCodN4ZUAtImT7pBEVBiYomwSd9VGcPSpXdfAsbk0gKcPFlxg/tGxBxWrO7F1tKeUOVtrx0XuTSdLWfbobQu3GLyyj7Cita9l8gd8GopNH1urNeO0BqqmyW1hDaQm/G+ys9Xv6JN0xlYR60BFsfugrxCPG+2G1PEIok2m4traFfVB9eZp2jz7/0107nZv5sxRY5D+k0hcwEwgyYUK7TItCqA8Fq4foa8hniBqFnab+WyHoeArpYMclGB5xWyKjevd8HiPfP3VTuaG216A8NJAoIBACbnSI0GUZraDRAzLFfVbRpSk9fHvj3JQ9HsiyNdmU0eB6rhdURZgmQKNmWG/oTlKQS8a4zn30HrzK+zfcs97RsNXkhDiTgtNgGEghp/IN0J4gUvAw4Ghr7YMXVgicda8YHL4hUlziZszdzNZizt/diVxBa3evpHlzHLkFNJFXCa7l9zCAulcA3i8qU2qV0bjHuX7YYfEVAnNzygR+B5rip9MPF5S3Gix7A0ygPu2foC8JxIdDfoalf9iY3MdxL7QhctXtGhwPacXbZbBOQBjuU2LlbZbwgTuV0AhlzotYRh8V/kUfLpILx3GPST6CNGr1JHoxdGDF4lchF2gUpJIKY=
    - keyId: RSA20200618_02
      keyType: RSA
      algorithm: RS256
      publicKey: MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAlJdZT4hSBn9koxngVLKnWa497E96RWDyQgQs2aFGvpAOQfyawKOHQ9XF5UmX5aSPd2j2kBeFq0w1LioximueujQS6YfIUOZRr2SNNKwusNblbvGziaow3WkHSbwrDpUZOsvzp+mS5dr020kHAJAoU79dJBaoDuADYgzPUuLy7YLwsFvxU5F2zysInCgotDsLUrcNmHiQPfMiX1+L4ogDUhv8E0nPVJ6F0vHfdmvf4UholhA27bGVupdafQkcmpEY0zgmedaMQD74S7+p5OPWrh5tsUyCk+tPjF5UsEi8ifORUcvBLPIgZKUVIVKyP9OXEMz3YBxtbtgeTK7FaMYEtwN/Ezhz8yCdHfvgJ6+V/ILKU01MWlCL9tby911u2F4A5/B971U5hjMdYrBGnT8F+g7dvqwOhBgoVJdSJFenB7NjeUr/vlg/ecjmObfOjFtswccYZ8+lSrCzJLczwdjzpdaZKLU56O81ID5lijk9OsIMu5FMOD/VW2Oy7QruQfmybh2xZ2LVEpMqX0nYJA9Wkchd0iegTzhut2O0raRk4kndetd+8NZ/uXvjTsPM4/0DVmuZ9izrckyUICvUmeuUXuTnA2XnvxIwQ09UUku69aksIZAI+/fBHtclnLYVz1VBCe+t9LLCCRqrNEkgv8LL6E6NFKCEj4fbjWPFQ+5O1QsCAwEAAQ==
      privateKey: MIIJQwIBADANBgkqhkiG9w0BAQEFAASCCS0wggkpAgEAAoICAQCUl1lPiFIGf2SjGeBUsqdZrj3sT3pFYPJCBCzZoUa+kA5B/JrAo4dD1cXlSZflpI93aPaQF4WrTDUuKjGKa566NBLph8hQ5lGvZI00rC6w1uVu8bOJqjDdaQdJvCsOlRk6y/On6ZLl2vTbSQcAkChTv10kFqgO4ANiDM9S4vLtgvCwW/FTkXbPKwicKCi0OwtStw2YeJA98yJfX4viiANSG/wTSc9UnoXS8d92a9/hSGiWEDbtsZW6l1p9CRyakRjTOCZ51oxAPvhLv6nk49auHm2xTIKT60+MXlSwSLyJ85FRy8Es8iBkpRUhUrI/05cQzPdgHG1u2B5MrsVoxgS3A38TOHPzIJ0d++Anr5X8gspTTUxaUIv21vL3XW7YXgDn8H3vVTmGMx1isEadPwX6Dt2+rA6EGChUl1IkV6cHs2N5Sv++WD95yOY5t86MW2zBxxhnz6VKsLMktzPB2POl1pkotTno7zUgPmWKOT06wgy7kUw4P9VbY7LtCu5B+bJuHbFnYtUSkypfSdgkD1aRyF3SJ6BPOG63Y7StpGTiSd16137w1n+5e+NOw8zj/QNWa5n2LOtyTJQgK9SZ65Re5OcDZee/EjBDT1RSS7r1qSwhkAj798Ee1yWcthXPVUEJ7630ssIJGqs0SSC/wsvoTo0UoISPh9uNY8VD7k7VCwIDAQABAoICAHAn6Q6iC5/B6nk9n9juXGjRnwXOW7EgYts3gY7nL5nI7Coce8Zp6EBojA3sRY3dbzinbmwGhSttwzpMOMaNQuqzQY8poSaHIiLsF7UpPbjXC6h5IZYIcwe8LfcW470HB1sc9JXKNMnwQh9+eJ2RMg88gxYpT8KijYslthuPF+P0kK3dSENWqcHnboFHwql/Y6WUa9upLN7FtS0d1l0vYqpIWzVH4gmx+brmPFCLThoiaGbUaFFzWFvVwERea0uzt3Q+jrQqIASiQxIR4i/VVYZpi0xnPqxd0dZWoT/KNx09TnPaAr5lJ9Qv0sorPEX29LCGtTXDX0pqMDybMoBJ7uX5mrhOdQze/bNe/1T7FSBBZIzVlmlb49XIxxnsrDiFQGRe5Op4udflw3zYKCzkjaAw6LDkDKt7veDThja7QREfHgPN8bFnC4sP2gV/TOgSCuF9x1lRbVj977IrCqDiSpcGuzBbBrWhetPZ2vwyHZr0eaMl/8ggg3wr3TnQ3UOLwe+8+mJKhNv235nralDC9xp2RnEgHibuQ37Uw03CYNNZtkWktK0W6mVR9RMAIZobWscxWMBd4LxM+t8uEJwIKkFGI5I5vVYVOHQnVs2zM0j6hkFxYQ66qGcDgMvgQM0iQVwVmWsZhr8fgPqAlAHezLE+gR4n7UHQPLLkqig9aHERAoIBAQDSusTJGKNgNPjN5MyBclqW1vBfNEC8wMLWuiiqX5lJXaEMxwu/dhmCIWSgzSrmXQBgI6rTVuYzILOa8mVeO0Lkd6Yw5zfyUTMAd8Qn9cc+bHkfo2WACpPuoezsZaJNBFPPT3GB+7L5dhvoSZWL26CCe6LSvsT46H3uq++gLlGO81b+IZ3/tMFn7kwLi3vzDWh2ZaFQ3K05jgLBZ+Lmfd6mnb8SSfPm9P2xUIlVQQvP2t2ubPETgz/6imDZZJo7jBepr9bQTrkXTHcpj/7NcqmYxRhYxlMFBF4/kFBEbgK7UKZRotuu53tqFz7wF0+eOBvdn2OjHQVdMyq4LjV3akAZAoIBAQC0gzv6u4F+vcgy7kyhdPa0KdagGRFk0VkFVedcPCp11pc05VGXGNEYx9rJ0Qk+yWYpX68VC+RBDC4YVH5tXH1f3yqj3dTlfmYwYSRHcFvq/RE4MRmYXnJofe1NXYcKP3TMez3Uvn6eSeQOKOIRHOmEE+f4Y/x4HgKU/LFnVsMXvp87CopNa7ojYDblHqdZKXdqq8r6d1sSrlCDjGWxcVe4lTxaR/y0dwKAwgP6Uw0JKQRyd6mv392/1WJZuFTjN+snFxDGzjWf+uXACfKNUk9l2ofGxonGQuD6kyTOnmDf748xRjXEwPLU+XGB7avEWOz4oT2JbUPJdyiXuOsJmFLDAoIBAQCzFvmA8kh+zeYZjXZkGNx2TysvrgfKooOz27gNu3tZh5IEevE4AVWCa4DKzDLGXomgKw/V1oeDMiqR56lQoUqjQjBiZU79yBZxMlfpog53tdZmlgYAAH1ilAj3ixSZIbFcgWa1EkUzjzX+fvLyTnAmFI73Thu2clf8S/E1j8fOlm37QnS1yVeJTVMhiKSJln6OCKdFQpaRUGh1GCYUvypHLc8h6um3AcTNOeXNJ5+zQY2e3IUxkR0BfzL57m7JZrEBjCgjFpRlAZ5QG0lwLx+FbxPW9o29uM2kdbBRx7DYop0GykKrbZ1MN39MqnMGwyajff8+s75IS+DlcJgN6aWZAoIBAEe5PUPK7REm5z0VYm1kxAGh/h1u2HJunCh6kYscfOKFeV8THvAidDKcdlpqLHo+G9GkqzR5nSAbbtVL/VAGx+ooChFCOy1Uo9XlQzz/cAZWt1jUaY8ZN+w83OU4nEd+HzKAZXj6l+TdBzh5FhommsJYBnuzfsVbZzs7jGG7H5l3rF0ROxK4EyWrPSScoXHUABbqW6RZeF5b1LHwPxfaKTi2U1yr7cTm5J+0d1AnX66cFaBF265+DOYEKyfrDg+aUF0f1RKpLLV8Q32idjWg1ttpkTlx+ZxFRo9Jl/5g/6z6yrKRaxvabqIg2vD9Npq1mrLPnlvUhnKuXfqrBvixBXECggEBAIM4dABNIGdVvC0TOX8g27eoNOSEf3i85hiX6edrWkNYJ7SfiZYpHqGuYcb7neOjmMZWf4mvFNiH0WgNCsFD847afIK7tWRkCK+uClTiEqPkrYo9jGok8HiIpLBqwLSrSm1IS79qBsGvXWn7snBRAmQBKUwsLOvgrX+5IfHZPU9zut/A+bLByhZ8uHKOmcMttzR20o875QVQXvWeOjEaFZBzfdHyzCmXdmrofYKChjlZm5e/TZy4HZo6voASMNPHI0pnfYPUi80DHyxpqPWZBgzIePO/Y2zKQB1hXmalmLKRJfnpE6n9MtqATnTIaQnlTM0AwLcHWp0BfPcYXun1UlA=

app:
  auth:
    client:
      jwt:
        issuer: moneytap-idm
        jwkUrl: http://localhost:8081/auth/certificates
        jwkCacheTimeInMinutes: 60

sentry:
  dsn: https://75c6192a80ff4e5aa022bf422d485983@o567854.ingest.sentry.io/5714686
  traces-sample-rate: 0.2
  logging:
    minimum-event-level: warn
    minimum-breadcrumb-level: debug
    send-default-pii: true
  environment: dev
  use-git-commit-id-as-release: true


environment:
  server:
    id: local

spring:
  liquibase:
    enabled: true
  servlet:
    multipart:
      enabled: false
  jpa:
    open-in-view: false
  main:
    allow-bean-definition-overriding: true
reactivate:
  cardIssued:
    fetch: false
    startDate: "2021-01-01"
    endDate: "2021-01-30"

infobip:
  smsBaseUrl: https://dummy_url.in
  voiceCredential: Basic DKJENnOEM=+NKEKWKW

mt:
  hibernate:
    cache:
      enabled: false
      provider:
        config: hibernate-redis.properties
  cronEnabled: false
  otpService: "fecOtpService"
  ifscApi: "defaultIfscApi"
  queueProvider: "AWS_SQS"
  fullname:
    regx: "^a-zA-Z"
  pattern:
    mobile: "^[987654]{1}[\\d]{9}$"
  validation:
    name:
      length:
        min: 2
        max: 78
  sanatization:
    name: true



partner:
  default:
    panValidationEnabled: true
    country: "INDIA"
    maxWithrawalLimit: 200000
    impsOtpVerificationRequired: true
    beneficiaryRequired: true
    maxPercentageForLimitUsage: 100
  rbl:
    panValidationEnabled: true
  dmi:
    panValidationEnabled: false
  fec:
    panValidationEnabled: false
    country: "VIETNAM"
    maxWithrawalLimit: 100000000
    impsOtpVerificationRequired: true
    beneficiaryRequired: false
    minimumIncomeAllowed: 3000000
    isPilotPhase: true
    isUat: true

vmg:
  fetch:
    enable: false
    NumberOfQueryPerPage: 50
    VmgFetchFromDate: 2020-08-02
    VmgFetchToDate: 2020-12-29

cloud:
  aws:
    sqs:
      endpoint: http://localhost:9324
      credentials:
        accessKey: ""
        secretKey: ""
    s3:
      accessKey: "1234567890123456"
      secretKey: "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
      endpoint: http://localhost:9000
      bucketName: s3docs
      maxConnections: 20
      clients:
        -
          bucketName: s3docs
          useDefault: true
        -
          bucketName: repaymentCash
          accessKey: 1234567890123456
          secretKey: ABCDEFGHIJKLMNOPQRSTUVWXYZ
          baseUrl: http://localhost:9000
          maxConnections: 20
        -
          bucketName: bancaproducts
          accessKey: 1234567890123456
          secretKey: ABCDEFGHIJKLMNOPQRSTUVWXYZ
          baseUrl: http://localhost:9000
          maxConnections: 20

freshdesk:
  baseurl: http://localhost:9049
  cc-email: hello@moneytap.vn

otpSmsProvider: valueFirst
transactionalSmsProvider: valueFirst
defaultSmsProvider: smsInfy
motpSmsProvider: smsInfy

transactional:
  url: http://api.myvaluefirst.com/psms/servlet/psms.JsonEservice
  username: moneytapxmlotp
  password: mnytp031
otp:
  url: http://api2.myvaluefirst.com/smpp/sendsms
  username: moneytaphtpotp
  password: mntap567


apns:
    certificatePath: /home/user/Downloads/prod_apns.p12
    password: moneytap@123

salvage:
  waiting:
    hours: 3
  enabled: false

---

spring:
  profiles: test
  datasource:
    username: mwyn
    password: nywm
    database: cashindb
    port: ${DB_PORT:25432}
    server: ${DB_HOST:localhost}
redis:
  port: 26379
cloud:
  aws:
    sqs:
      endpoint: http://localhost:29324
    s3:
      endpoint: http://localhost:29000
logging:
  file: /tmp/rest.log

---
spring:
  profiles: dev
sentry:
  environment: dev

---
spring:
  profiles: prod
sentry:
  environment: prod
